title: "Remote theme example"
remote_theme: just-the-docs/just-the-docs
color_scheme: "light"
search_enabled: false
logo: "/assets/images/CircuitFlyer.png"
callouts:
  warning:
    title: Warning
    color: red
heading_anchors: false
